##############################
# Please edit this line to "not_sample_anymore" to make the bot run
is_example_config_or_not: "not_sample_anymore"
##############################
bot_token: "1650411260:AAEOYdYhvECeZa52cNSX0f7rAf3NRh724zg"
api_key: '2498883'
api_hash: '5aff214890cf9e5affc6a51167496728'
owner_id: 1287904152
owner_username: "itsabdulkader"
message_dump: "-502868974"
load: []
no_load: []
strict_antispam: False
workers: 4
del_cmds: False
sw_api: 'Go1H3muN7qvmv~_BYOP5zZG_0yMcCDRXybeIp9Pw4CgRAMZHsaGxTsSSTyfZCyEA'

# Database
database_url: "postgres://orktegxvjeenhc:a100030a9bf07cddb8c352d168704a67333405eb2d6c65c2cb0c48df24239e42@ec2-34-239-33-57.compute-1.amazonaws.com:5432/d431ukup8ii5ur"

# Permission
sudo_users: [1287904152]
whitelist_users: []
